import yaml
from crewai import Agent

# Carregar YAML
with open("agents.yaml", "r") as file:
    agents_data = yaml.safe_load(file)

# Criar agentes a partir do YAML
data_collector = Agent(
    role=agents_data['data_collector']['role'],
    goal=agents_data['data_collector']['goal'],
    backstory=agents_data['data_collector']['backstory'],
    tools=agents_data['data_collector']['tools']
)

data_analyst = Agent(
    role=agents_data['data_analyst']['role'],
    goal=agents_data['data_analyst']['goal'],
    backstory=agents_data['data_analyst']['backstory'],
    tools=agents_data['data_analyst']['tools']
)

data_visualizer = Agent(
    role=agents_data['data_visualizer']['role'],
    goal=agents_data['data_visualizer']['goal'],
    backstory=agents_data['data_visualizer']['backstory'],
    tools=agents_data['data_visualizer']['tools']
)
